course_monitor/people_app/urls.py
from django.urls import path
# from .views import *
from .views import log_in, base, log_out, register_user, permissions_test, ViewCityTimezone, UpdateCityTimeZone, \
    DeleteCityTimeZone, CreateCity, CreateTimeZone, CreateCityTimeZone, ViewListCat, \
    UpdateListCat, FlowCreate, FlowUpdate, FlowDelete, ViewTaskCat, UpdateTaskCategory, UpdateBonusCategory, \
    ViewPaymentStatus, \
    UpdatePaymentStatus, ViewBonusCat, ViewTaskCat, ViewFlow, ViewLevel, CreateLevel, UpdateLevel, DeleteLevel, \
    ViewUser, DeleteUser, ViewStudentStatus, CreateStudentStatus, UpdateStudentStatus, DeleteStudentStatus, UpdateUser, \
    create_student, ViewPayment, PaymentCreate

urlpatterns = [
    path('', log_in, name='login'),
    path('base/', base, name='base'),
    path('logout/', log_out, name='logout'),
    path('register/', register_user, name='registration'),
    path('update_user/<pk>', UpdateUser.as_view(extra_context={
    'title': 'User Update', 'cancel': 'base'}
    ), name='update_user'),
    path('permissions/', permissions_test, name='permissions'),
    path('cities/', ViewCityTimezone.as_view(), name='cities'),
    path('cities/<pk>', UpdateCityTimeZone.as_view(extra_context={'title':'City','cancel': 'cities'}),
         name='cities_update'),
    path('cities_del/<pk>', DeleteCityTimeZone.as_view(), name='cities_del'),
    path('reg_city/', CreateCity.as_view(), name='reg_city'),
    path('reg_timezone/', CreateTimeZone.as_view(), name='reg_timezone'),
    path('reg_citytimezone/', CreateCityTimeZone.as_view(), name='reg_citytimezone'),
    path('list_category/', ViewListCat.as_view(extra_context={'title': 'List Category', 'update': 'list_update'}),
         name='list_cat'),
    path('list_update/<pk>',
         UpdateListCat.as_view(extra_context={'title': 'List Category Update', 'cancel': 'list_cat'}),
         name='list_update'),
    path('flow_create/', FlowCreate.as_view(), name='flow_create'),
    path('flow_update/<pk>', FlowUpdate.as_view(extra_context={'title':'Flow'
                                                               ,'cancel':'flow'}), name='flow_update'),
    path('flow_delete/<pk>', FlowDelete.as_view(), name='flow_delete'),
    path('payment_status/',
         ViewPaymentStatus.as_view(extra_context={'title': 'Payment status', 'update': 'payment_status_update'}),
         name='payment_status'),
    path('payment_status_update/<pk>',
         UpdatePaymentStatus.as_view(extra_context={'title': 'Payment Status Update', 'cancel': 'payment_status'}),
         name='payment_status_update'),
    path('bonus_category/', ViewBonusCat.as_view(extra_context={'title': 'Bonus Category',
                                                                'update': 'bonus_category_update'}), name='bonus_cat'),
    path('bonus_category_update/<pk>',
         UpdateBonusCategory.as_view(extra_context={'title': 'Bonus Category Update', 'cancel': 'bonus_cat'}),
         name='bonus_category_update'),
    path('task_category/', ViewTaskCat.as_view(extra_context={'title': 'Task Category',
                                                              'update': 'task_category_update'}), name='task_category'),
    path('task_category_update/<pk>',
         UpdateTaskCategory.as_view(extra_context={'title': 'Task Category Update', 'cancel': 'task_category'}),
         name='task_category_update'),
    path('flow/', ViewFlow.as_view(), name='flow'),
    path('level/', ViewLevel.as_view(), name='level'),
    path('create_level/', CreateLevel.as_view(), name='create_level'),
    path('update_level/<pk>', UpdateLevel.as_view(), name='update_level'),
    path('delete_level/<pk>', DeleteLevel.as_view(), name='delete_level'),
    path('users/', ViewUser.as_view(), name='users'),
    path('delete_user/<pk>', DeleteUser.as_view(), name='delete_user'),
    path('student_status/', ViewStudentStatus.as_view(extra_context={'title': 'Student Status',
                                                                     'update': 'update_student_status'}),
         name='student_status'),
    path('create_student_status/', CreateStudentStatus.as_view(), name='create_student_status'),

    path('update_student_status/<pk>', UpdateStudentStatus.as_view(extra_context={'title': 'Student Status Update', 'cancel': 'student_status'}), name='update_student_status'),
    path('delete_student_status/<pk>', DeleteStudentStatus.as_view(), name='delete_student_status'),
    path('create_student/<pk>', create_student, name='create_student'),
    path('payment/', ViewPayment.as_view(), name='payment'),
    path('payment_create/', PaymentCreate.as_view(), name='payment_create'),

]

course_monitor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('course_monitor.people_app.urls')),
    path('admin/', admin.site.urls),
]

course_monitor/people_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group


class City(models.Model):
    name = models.CharField(max_length=30, null=False, blank=False)
    description = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name


class TimeZone(models.Model):
    name = models.CharField(max_length=3, null=False, blank=False, unique=True)
    description = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name


class CityTimeZone(models.Model):
    """
    must have city_id, time_zone_id
    """
    city = models.ForeignKey(City, on_delete=models.RESTRICT, null=False, blank=False)
    time_zone = models.ForeignKey(TimeZone, on_delete=models.RESTRICT, null=False, blank=False)
    offset = models.CharField(max_length=3, null=False, blank=False)

    def __str__(self):
        return f'City name ({self.city.name}) Name ({self.time_zone.name}) Offset ({self.offset})'


class UserSocialNetwork(models.Model):
    name = models.CharField(max_length=50)
    link = models.TextField()

    def __str__(self):
        return self.link


class User(AbstractUser):

    account_name = models.CharField(max_length=70, null=False, blank=False)
    nick = models.CharField(max_length=50, null=True, blank=True)
    name = models.CharField(max_length=70, null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(null=True, blank=True, unique=True)
    sex = models.CharField(max_length=2, null=True, blank=True)
    city = models.ForeignKey(City, on_delete=models.RESTRICT, null=True, blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(null=True, blank=True)
    link_to_social_network = models.ManyToManyField(UserSocialNetwork)

    REQUIRED_FIELDS = ['username']
    USERNAME_FIELD = 'email'
# ==================================================


class Form(models.Model):
    """
    language choices
    """
    name = models.CharField(max_length=50, null=False, blank=False)
    description = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name


class Language(models.Model):
    """
    language choices
    """
    name = models.CharField(max_length=10, null=False, blank=False)
    description = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name


class Label(models.Model):
    """
    language choices
    """
    form = models.ForeignKey(Form, on_delete=models.RESTRICT)
    language = models.ForeignKey(Language, on_delete=models.RESTRICT)
    label_code = models.CharField(max_length=50, null=True, blank=True)
    label_translated = models.CharField(max_length=255, null=True, blank=True)
# ========================================================================


class PaymentStatus(models.Model):
    """
    name = full, partial, free, waiting
    """
    name = models.CharField(max_length=20, null=False, blank=False, unique=True)
    description = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name


class Payment(models.Model):
    payment_status = models.ForeignKey(PaymentStatus, on_delete=models.RESTRICT, null=False, blank=False)
    user = models.ForeignKey(User, on_delete=models.RESTRICT, null=False, blank=False)
    date_pay_due = models.DateTimeField(null=True, blank=True)
    paid_amount = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    comment = models.TextField(null=True, blank=True)
    date_paid = models.DateTimeField(null=True, blank=True)
    amount_debt = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    doc_name = models.CharField(max_length=20, null=True, blank=True, unique=True, default="Doc name")

    def __str__(self):
        return self.doc_name


class Flow(models.Model):
    """
    finish with attributes of valid_from to
    """
    code = models.CharField(max_length=10, null=False, blank=False)
    name = models.CharField(max_length=50, null=False, blank=False)
    description = models.CharField(max_length=255, blank=True, null=True)
    valid_from = models.DateTimeField(blank=True, null=True)
    valid_to = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return f'code({self.code})   name({self.name})   description({self.description})'


class Level(models.Model):
    """
    default = 0 (False)
    """
    flow = models.ForeignKey(Flow, on_delete=models.RESTRICT)
    name = models.CharField(max_length=15, null=False, blank=False)
    description = models.CharField(max_length=255, blank=True, null=True)
    started = models.BooleanField(default=0)

    def __str__(self):
        return self.name


class StudentStatus(models.Model):
    """
    Active, Cancelled, Finished,  Moved, Potential, Joined
    """
    name = models.CharField(max_length=15, null=False, blank=False, unique=True)
    description = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name


class Coach(models.Model):
    flow = models.ForeignKey(Flow, on_delete=models.RESTRICT)
    user = models.ForeignKey(User, on_delete=models.RESTRICT)

    def __str__(self):
        return self.user.account_name


class Student(models.Model):
    """
    Check the logic of the attributes
    especially creation date
    """
    user = models.ForeignKey(User, on_delete=models.RESTRICT)
    coach = models.ForeignKey(Coach, on_delete=models.RESTRICT, blank=True, null=True)
    flow = models.ForeignKey(Flow, on_delete=models.RESTRICT)
    student_status = models.ForeignKey(StudentStatus, on_delete=models.RESTRICT)
    level = models.ForeignKey(Level, on_delete=models.RESTRICT, blank=True, null=True)
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.account_name
# ===========================================================


class ListCategory(models.Model):
    """
    Task, Bonus
    """
    name = models.CharField(max_length=15, null=False, blank=False, unique=True)
    description = models.TextField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name


class ListN(models.Model):
    """
    Confirm logic of booleanfield
    """
    task_no = models.CharField(max_length=10, null=False, blank=False)
    name = models.CharField(max_length=70, null=False, blank=False)
    description = models.TextField(blank=True, null=True)
    complex = models.BooleanField(default=0)
    is_active = models.BooleanField(default=1)
    list_category = models.ForeignKey(ListCategory, on_delete=models.RESTRICT)

    def __str__(self):
        return self.name


class TaskCategory(models.Model):
    """
    Main, Additional, Marathon
    """

    name = models.CharField(max_length=10, null=False, blank=False, unique=True)
    description = models.TextField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    """
    check attributes
    """
    code = models.CharField(max_length=10, null=False, blank=False)
    list = models.ForeignKey(ListN, on_delete=models.RESTRICT)
    issued = models.BooleanField(default=0)
    link_in_base = models.TextField(null=True, blank=True)
    link_in_chat = models.TextField(null=True, blank=True)
    flow = models.ForeignKey(Flow, on_delete=models.RESTRICT)
    task_category = models.ForeignKey(TaskCategory, on_delete=models.RESTRICT)
    level = models.ForeignKey(Level, on_delete=models.RESTRICT, null=True, blank=True)
    issue_date = models.DateTimeField()
    due_date = models.DateTimeField()

    def __str__(self):
        return self.code


class BonusCategory(models.Model):
    """
    Artifact, Team, Marathone
    """
    name = models.CharField(max_length=15, null=False, blank=False, unique=True)
    description = models.TextField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name


class TaskCodeLastNo(models.Model):
    task_category = models.ForeignKey(TaskCategory, on_delete=models.RESTRICT, null=True, blank=True)
    task_sequence_no = models.IntegerField(default=0, null=True, blank=True)
    flow = models.ForeignKey(Flow, on_delete=models.RESTRICT, null=True, blank=True)
    bonus_category = models.ForeignKey(BonusCategory, on_delete=models.RESTRICT, null=True, blank=True)
    bonus_sequence_no = models.IntegerField(default=0, null=True, blank=True)
    level = models.ForeignKey(Level, on_delete=models.RESTRICT, null=True, blank=True)
    level_sequence_no = models.IntegerField(default=0, null=True, blank=True)

    def __str__(self):
        if self.task_category:
            return self.task_sequence_no
        elif self.bonus_category:
            return self.bonus_sequence_no
        else:
            return self.level_sequence_no


class AdditionalMaterials(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    description = models.CharField(max_length=255, blank=True, null=True)
    link = models.TextField(null=True, blank=True)
    flow = models.ForeignKey(Flow, on_delete=models.RESTRICT)
    task = models.ForeignKey(Task, on_delete=models.RESTRICT, blank=True, null=True)

    def __str__(self):
        return self.name


class PlanedTaskAmount(models.Model):
    amount = models.IntegerField(default=0)
    task_category = models.ForeignKey(TaskCategory, on_delete=models.RESTRICT)
    level = models.ForeignKey(Level, on_delete=models.RESTRICT, blank=True, null=True)
    flow = models.ForeignKey(Flow, on_delete=models.RESTRICT)

    def __str__(self):
        return self.amount
# =========================================================


class Bonus(models.Model):
    code = models.CharField(max_length=15, null=False, blank=False)

course_monitor/people_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>

.emp-profile{
    padding: 3%;
    margin-top: 3%;
    margin-bottom: 3%;
    border-radius: 0.5rem;
    background: #fff;
}
.profile-img{
    text-align: center;
}
.profile-img img{
    width: 70%;
    height: 100%;
}
.profile-img .file {
    position: relative;
    overflow: hidden;
    margin-top: -20%;
    width: 70%;
    border: none;
    border-radius: 0;
    font-size: 15px;
    background: #212529b8;
}
.profile-img .file input {
    position: absolute;
    opacity: 0;
    right: 0;
    top: 0;
}
.profile-head h5{
    color: #333;
}
.profile-head h6{
    color: #0062cc;
}
.profile-edit-btn{
    border: none;
    border-radius: 1.5rem;
    width: 70%;
    padding: 2%;
    font-weight: 600;
    color: #6c757d;
    cursor: pointer;
}
.proile-rating{
    font-size: 12px;
    color: #818182;
    margin-top: 5%;
}
.proile-rating span{
    color: #495057;
    font-size: 15px;
    font-weight: 600;
}
.profile-head .nav-tabs{
    margin-bottom:5%;
}
.profile-head .nav-tabs .nav-link{
    font-weight:600;
    border: none;
}
.profile-head .nav-tabs .nav-link.active{
    border: none;
    border-bottom:2px solid #0062cc;
}
.profile-work{
    padding: 14%;
    margin-top: -15%;
}
.profile-work p{
    font-size: 12px;
    color: #818182;
    font-weight: 600;
    margin-top: 10%;
}
.profile-work a{
    text-decoration: none;
    color: #495057;
    font-weight: 600;
    font-size: 14px;
}
.profile-work ul{
    list-style: none;
}
.profile-tab label{
    font-weight: 600;
}
.profile-tab p{
    font-weight: 600;
    color: #0062cc;
}
.modal-login {
	color: #636363;
	width: 300px;
}
.modal-login .modal-content {
	padding: 20px;
	border-radius: 5px;
	border: none;
}
.modal-login .modal-header {
	border-bottom: none;
	position: relative;
	justify-content: center;
}
.modal-login h4 {
	text-align: center;
	font-size: 26px;
}
.modal-login  .form-group {
	position: relative;
}
.modal-login i {
	position: absolute;
	left: 13px;
	top: 11px;
	font-size: 18px;
}
.modal-login .form-control {
	padding-left: 40px;
}
.modal-login .form-control:focus {
	border-color: #00ce81;
}
.modal-login .form-control, .modal-login .btn {
	min-height: 40px;
	border-radius: 3px;
}
.modal-login .hint-text {
	text-align: center;
	padding-top: 10px;
}
.modal-login .close {
	position: absolute;
	top: -5px;
	right: -5px;
}
.modal-login .btn, .modal-login .btn:active {
	border: none;
	background: #00ce81 !important;
	line-height: normal;
}
.modal-login .btn:hover, .modal-login .btn:focus {
	background: #00bf78 !important;
}
.modal-login .modal-footer {
	background: #ecf0f1;
	border-color: #dee4e7;
	text-align: center;
	margin: 0 -20px -20px;
	border-radius: 5px;
	font-size: 13px;
	justify-content: center;
}
.modal-login .modal-footer a {
	color: #999;
}
<!--a {-->
<!--  text-decoration: none;-->
<!--}-->

<!--nav {-->
<!--  font-family: monospace;-->
<!--}-->

<!--ul {-->
<!--  background: darkorange;-->
<!--  list-style: none;-->
<!--  margin: 0;-->
<!--  padding-left: 0;-->
<!--}-->

<!--li {-->
<!--  color: #fff;-->
<!--  background: darkorange;-->
<!--  display: block;-->
<!--  float: left;-->
<!--  padding: 1rem;-->
<!--  position: relative;-->
<!--  text-decoration: none;-->
<!--  transition-duration: 0.5s;-->
<!--}-->

<!--li a {-->
<!--  color: #fff;-->
<!--}-->

<!--li:hover,-->
<!--li:focus-within {-->
<!--  background: red;-->
<!--  cursor: pointer;-->
<!--}-->

<!--li:focus-within a {-->
<!--  outline: none;-->
<!--}-->

<!--ul li ul {-->
<!--  background: orange;-->
<!--  visibility: hidden;-->
<!--  opacity: 0;-->
<!--  min-width: 5rem;-->
<!--  position: absolute;-->
<!--  transition: all 0.5s ease;-->
<!--  margin-top: 1rem;-->
<!--  left: 0;-->
<!--  display: none;-->
<!--}-->

<!--ul li:hover > ul,-->
<!--ul li:focus-within > ul,-->
<!--ul li ul:hover,-->
<!--ul li ul:focus {-->
<!--  visibility: visible;-->
<!--  opacity: 1;-->
<!--  display: block-->
<!--}-->

<!--ul li ul li {-->
<!--  clear: both;-->
<!--  width: 100%;-->
<!--}-->

/* fallback */
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/materialicons/v126/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2) format('woff2');
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}



    </style>
</head>
<body>
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

course_monitor/people_app/templates/cities.html
{% extends 'base.html' %}
{% block content %}

<div class="modal-dialog">

    <div class="modal-content">
        <div class="modal-header"><a href="{% url 'reg_citytimezone' %}" class="btn btn-info">Register</a></div>
        <table border>
            <thead>
            <tr>
                <th>city</th>
                <th>time zone</th>
                <th>offset</th>
                <th>description</th>
                <th>action</th>
            </tr>
            </thead>
            <tbody>
            {% if cities %}
            {% for city in cities %}
            <tr>
                <td>{{city.city.name}}</td>
                <td>{{city.time_zone}}</td>
                <td>{{city.offset}}</td>
                <td>{{city.city.description}}</td>
                <td>
                    <a href="{% url 'cities_update' city.id %}" class="btn btn-success">Update</a>
                    <a href="{% url 'cities_del' city.id %}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr></tr>
            {% endif %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

course_monitor/people_app/templates/content.html
{% extends 'base.html' %}
{% block content %}
<div class="container emp-profile">
    <form method="post">
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS52y5aInsxSm31CvHOFHWujqUx_wWTS9iM6s7BAm21oEN_RiGoog"
                         alt=""/>
                    <div class="file btn btn-lg btn-primary">
                        Change Photo
                        <input type="file" name="file"/>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-head">
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab"
                               aria-controls="home" aria-selected="true">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab"
                               aria-controls="profile" aria-selected="false">Timeline</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2">
                <a href="{% url 'update_user' user.id %}" class="btn btn-lg">Edit Profile</a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="profile-work">
                    <p>WORK LINK</p>
                    {% if user.link_to_social_network %}
                    {% for link in user.link_to_social_network.all %}
                    <a href="https://{{link}}">{{link}}</a><br/>
                    {% endfor %}

                    {% endif %}
                </div>
            </div>
            <div class="col-md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Account name</label>
                            </div>
                            <div class="col-md-6">
                                {% if user.account_name == None %}
                                <p> - - - - </p>
                                {% else %}
                                <p>{{user.account_name}}</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Nice</label>
                            </div>
                            <div class="col-md-6">
                                {% if user.nick == None %}
                                <p> - - - - </p>
                                {% else %}
                                <p>{{user.nick}}</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Name</label>
                            </div>
                            <div class="col-md-6">
                                {% if user.name == None %}
                                <p> - - - - </p>
                                {% else %}
                                <p>{{user.name}}</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Email</label>
                            </div>
                            <div class="col-md-6">
                                {% if user.email == None %}
                                <p> - - - - </p>
                                {% else %}
                                <p>{{user.email}}</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Phone</label>
                            </div>
                            <div class="col-md-6">
                                {% if user.phone == None %}
                                <p> - - - - </p>
                                {% else %}
                                <p>{{user.phone}}</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Status</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{user.groups.first}}</p>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Sex</label>
                            </div>
                            <div class="col-md-6">
                                {% if user.sex == None %}
                                <p> - - - - </p>
                                {% else %}
                                <p>{{user.sex}}</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>City</label>
                            </div>
                            <div class="col-md-6">
                                {% if user.city == None %}
                                <p> - - - - </p>
                                {% else %}
                                <p>{{user.city}}</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Creation date</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{user.creation_date}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Comments</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{user.comment}}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

course_monitor/people_app/templates/test_for_permissions.html
{% extends 'base.html' %}
{% block content %}
<div id="tableModal">
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
  <p>Table</p>
    </div>
  <div class="modal-body">
    <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      {% if perms.people_app.view_city %}
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      {% endif %}
      <td>
        {% if perms.people_app.change_city %}
          <a href="#" class="btn btn-primary">Update</a>
        {% endif %}
        {% if perms.people_app.add_city %}
          <a href="#" class="btn btn-warning">Create</a>
        {% endif %}
        {% if perms.people_app.delete_city %}
          <a href="#" class="btn btn-danger">Delete</a>
        {% endif %}
      </td>
    </tr>

  </tbody>
</table>
  </div>
    </div>
</div>
</div>
{% endblock %}